name: CI

on: pull_request

jobs:
  test:
    runs-on: macOS-15
    defaults:
      run:
        working-directory: ./TanoshiiRecipeKit
    steps:
    - uses: actions/checkout@v4
    - run: sudo xcode-select -switch /Applications/Xcode_16.4.app
    - run: swift build --build-tests
    - run: swift test --skip-build --enable-swift-testing --parallel
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./TanoshiiRecipeKit
    container: swift:latest
    steps:
      - uses: actions/checkout@v4
      - run: swift format lint -r -p -s .
